import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head><title>NewtonXDSA</title></head>
      <body className={inter.className}>
        <div style={{position: 'absolute', height: 90, backgroundColor: "#FFFFFF55", width: "100%", backdropFilter: "blur(10px)", flexDirection: 'row'}}>
          
          <div style={{marginLeft: 'auto', height: "100%", backgroundColor: 'green', alignItems: 'center', justifyContent: 'center', width: 500}}>
            
            

          </div>

        </div>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}
